[tox]
envlist =
  lint

[testenv:lint]
commands =
  black --check --diff .
  isort --check-only --diff .
  flake8
deps =
  -r requirements/requirements-lint.txt

[flake8]
max-line-length = 80
max-complexity = 10
