[tox]
requires =
  tox-gh-actions
envlist =
  lint
  py{38,39,310,311,312}-django42
  py{310,311,312,313,314}-django52
  py{312,313,314}-django60

[testenv]
commands =
  pytest
deps =
  django42: django==4.2.*
  django52: django==5.2.*
  django60: django==6.0.*
  -r requirements/requirements-dev.txt
setenv =
  PYTHONDONTWRITEBYTECODE=1

[testenv:lint]
commands =
  black --check --diff .
  isort --check-only --diff .
  flake8
deps =
  -r requirements/requirements-lint.txt

[gh-actions]
python =
  3.8: py38
  3.9: py39
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314, lint

[flake8]
max-line-length = 80
max-complexity = 10
