[tox]
envlist =
  lint
  py{38,39,310,311,312}-django42
  py{310,311,312,313,314}-django52

[testenv]
commands =
  pytest
deps =
  django42: django==4.2.*
  django52: django==5.2.*
  -r requirements/requirements-dev.txt
setenv =
  PYTHONDONTWRITEBYTECODE=1

[testenv:lint]
commands =
  black --check --diff .
  isort --check-only --diff .
  flake8
deps =
  -r requirements/requirements-lint.txt

[flake8]
max-line-length = 80
max-complexity = 10
